---
# Set your specific variables here.
# DON'T declare environment or site related variables here.
# They MUST be set in the inventory group_vars/

# Local settings
timezone: Europe/Paris
docker__path: /docker
