---
# Describe here all your required system and middleware installation tasks

- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"
  ignore_errors: true

- name: Set vm.swappiness in /etc/sysctl.conf
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ ubuntu__swappiness }}"
    state: present

- name: Set vm.vfs_cache_pressure in /etc/sysctl.conf
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ ubuntu__vfs_cache_pressure }}"
    state: present

- name: Refresh apt cache
  apt:
    update_cache: true

- name: Update all packages to the latest version
  apt:
    upgrade: dist 

- name: Install packages
  apt:
    name: "{{ apt_pkg }}"
    state: present

- name: Disable cloud-init
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    mode: u=rw,g=r,o=r
  ignore_errors: true

- name: Disable Ubuntu Motd News
  lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED='
    line: ENABLED=0
  ignore_errors: true

- name: Add group {{ ubuntu__user_group | default(ubuntu__user_name) }}
  group:
    name: "{{ ubuntu__user_group | default(ubuntu__user_name) }}"
    gid: "{{ ubuntu__user_gid | default(omit) }}"
    state: present
  when: ubuntu__user_name is defined

- name: Add user {{ ubuntu__user_name }} to groups {{ ubuntu__user_group | default(ubuntu__user_name) }}
  user:
    name: "{{ ubuntu__user_name }}"
    group: "{{ ubuntu__user_group | default(ubuntu__user_name) }}"
    uid: "{{ ubuntu__user_uid | default(omit) }}"
    shell: "{{ ubuntu__user_shell }}"
    create_home: "{{ ubuntu__user_home }}"
  when: ubuntu__user_name is defined

# - name: Allow default user to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#     validate: 'visudo -cf %s'